baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-083-advanced/"
languageCode = "en-us"
title = "cs-ej4101-fall-2019-083-advanced"
theme="hugo-universal-theme-master"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="Course"
    name = "Course"
    url  = "/course/"
    weight = 2

[[menu.main]]
    identifier = "Learning"
    name = "Learning"
    url  = "/learning/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4
