baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-083-advanced/"
languageCode = "en-us"
title = "cs-ej4101-fall-2019-083-advanced"
theme="hugo-grapes-master"

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = ""
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
    weight = 2

[params]
avatar = "img/tree.png"
