baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-083-advanced/"
languageCode = "en-us"
title = "cs-ej4101-fall-2019-083-advanced"
theme="hugo-universal-theme-master"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="Course"
    name = "Course"
    url  = "/course/"
    weight = 2

[[menu.main]]
    identifier = "Learning"
    name = "Learning"
    url  = "/learning/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4


    [[menu.topbar]]
        weight = 1
        name = "GitHub"
        url = "https://github.com/aaltomcc/cs-ej4101-fall-2019-083-advanced"
        pre = "<i class='fab fa-2x fa-github'></i>"

    [[menu.topbar]]
        weight = 2
        name = "Linkedin"
        url = "https://www.linkedin.com/in/arttu--heikura/"
        pre = "<i class='fab fa-2x fa-linkedin'></i>"


    [[menu.topbar]]
        weight = 4
        name = "Email"
        url = "arttu.e.heikura@aalto.fi"
        pre = "<i class='fas fa-2x fa-envelope'></i>"


        [params.topbar]
            enable = true
            text = """<p class="hidden-sm hidden-xs">Contact us on arttu.e.heikura@aalto.fi.</p>
              <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
              <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
              </p>
              """
[params]
logo = "img/logo.png"
logo_small = "img/logo.png"
style = "green"



[params.carousel]
    enable = true

[params.features]
    enable = true

    [params.testimonials]
        enable = true
        title = "Testimonials"
        subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."


        [params.see_more]
            enable = true
            icon = "far fa-file-alt"
            title = "Do you want to see more?"
            subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
            link_url = "http://your-site.com/more"
            link_text = "Check other homepages"

            [params.clients]
                enable = true
                title = "Our Partners"
                subtitle = "We have proudly collaborated with the following companies."
